# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "O'Neill Career Hub Resources Guide"
email: careerhb@indiana.edu
description: > # this means to ignore newlines until "baseurl:"
  The O'Neill School of Public and Environmental Affairs at Indiana University – Bloomington
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oneill-career-hub.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username: oneill-career-hub
google_analytics: UA-148188804-1
tipue_search:
  include:
    pages: true
    collections: [undergraduate,graduate]

# Build settings
markdown: kramdown
